services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
    networks:
      - tdt-network

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
    - DEFAULT_EMAIL=ofw98527@nezid.com
    #encounter error when didn't add below parameter.
    - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - tdt-network

  nginx:
    build: 
      context: ./nginx
    image: tdt-nginx-docker
    container_name: tdt-nginx
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - VIRTUAL_HOST=taipei-trip.ddns.net
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=taipei-trip.ddns.net
      - LETSENCRYPT_EMAIL=ofw98527@nezid.com

  flask:
    build:
      context: ./flask
    image: tdt-flask-docker
    container_name: tdt-flask
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    container_name: tdt-mysql
    networks:
      - tdt-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 20

networks:
  tdt-network:
  
volumes:
  certs:
  vhost:
  html:
  acme:
