services:
  nginx:
    build: 
      context: ./nginx
    image: tdt-nginx-docker
    container_name: tdt-nginx
    ports:
      - 3000:3000
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy

  flask:
    build:
      context: ./flask
    image: tdt-flask-docker
    container_name: tdt-flask
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    container_name: tdt-mysql
    networks:
      - tdt-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 20

networks:
  tdt-network:
