services:
  nginx:
    build: 
      context: ./nginx
    image: taipei-day-trip-reverse-proxy
    container_name: taipei-day-trip-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  flask:
    image: vkmouse/taipei-day-trip-backend
    container_name: taipei-day-trip-backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - backend.env

  frontend:
    image: vkmouse/taipei-day-trip-frontend
    container_name: taipei-day-trip-frontend

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    container_name: taipei-day-trip-mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 20

  redis:
    image: redis:alpine
    container_name: taipei-day-trip-redis
    command: ["redis-server", "--bind", "0.0.0.0"]
