services:
  nginx:
    build: 
      context: ./nginx
    image: tdt-nginx-docker
    container_name: tdt-nginx
    ports:
      - "80:80"
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy

  flask:
    build:
      context: ./flask
    image: tdt-flask-docker
    container_name: tdt-flask
    networks:
      - tdt-network
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    image: tdt-frontend-docker
    container_name: tdt-frontend
    networks:
      - tdt-network

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    container_name: tdt-mysql
    networks:
      - tdt-network
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot --password=$$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 20

  redis:
    image: redis:alpine
    container_name: tdt-redis
    networks:
      - tdt-network
    command: ["redis-server", "--bind", "0.0.0.0"]

networks:
  tdt-network:
